### ISSUE TITLE
Mobile app logs out when started offline

### ISSUE THREAD

**Issue by dormerod** [brisqapp/issue-tracker#23] opened 2022-03-25 09:04 UTC
**Brisqi version:** Build: 2.0.0 | Update: 0.3.1

**Brisqi plan:** standard

**Device:** mobile

**Environment:** Android 11

## What happened?

While testing whether #22 is an issue on mobile, the app asked me to log in again.

I reconnected to the internet, had to log back in and could then use Brisqi normally. I then closed the app, repeated the offline start and was logged out again.

## What I expected to happen

I thought that Brisqi would be able to function without the internet and would store and forward any changes once it was back online.

*Note: this isn't a theoretical problem. I'm using Brisqi in an area where cell coverage is quite patchy.*

## Steps to reproduce

To reproduce:

1. use a mobile device (Android maybe)
2. make sure you're logged in to Brisqi
3. completely close the app
4. disable wifi and mobile data
5. start the Brisqi app
6. note that Brisqi asks you to log in again.

**Comment by ashgrover** [comment] 2022-03-27 21:36
@dormerod 

This issue was fixed a while back and I'm not able to reproduce it on my end. With the latest version of the mobile app you shouldn't see this issue. Could you please go the to the Settings screen(⚙icon on top right corner) and tell me Build and Update version?

**Comment by dormerod** [comment] 2022-04-11 02:15
Thanks Ash, and sorry for the slow reply. Got caught up with work...

I forgot that there would likely be an OTA update for mobile. I'm running:

**Build: 2.0.0**
**Update 0.3.1**

Just tried restarting the mobile app a few times and letting it sit to see if it would download a new OTA. It seems like 0.3.1 is the newest version I can get at the moment.

Also just retested this a few times and it's still an issue on this version.

In this particular case, our home internet is solid because we need it for work, but if I drive into some of the nearby towns and want to check what I can get done while there, there's a high chance of getting logged out. At the moment the workaround is to copy all the tasks onto a paper note before leaving home.

**Comment by ashgrover** [comment] 2022-04-12 06:06
@dormerod  Thanks for getting back with the information I asked. Those are latest updates so it is really odd that Brisqi is logging you out. I couldn't reproduce this issue at all on my end. I tested on Pixel 2, Pixel 3, Pixel 5, Galaxy A8, and iPhone, basically any phone I could get my hands on from friends and family and I still couldn't reproduce it on any of them. And this issue is concerning to me because I had especially fixed it a few months ago. The issue which I had fixed was that Brisqi mobile app would remain logged in up to an hour and it would then log out after if started offline. After the fix I made that issue got resolved and I didn't see it happening again. 

May be you're hitting a rare corner case which might be causing Brisqi mobile app to logout, the only issue is that I'm unable to reproduce it. However, I'll try my best and keep looking into it and change some things which may or may not fix it as it'll be based on speculation on what could be happening. 

Edit: I forgot to ask, what phone are you using if you don't mind telling me?

Thanks again,
Ash

**Comment by dormerod** [comment] 2022-04-12 06:10
Thanks Ash, I'll email you.

**Comment by ashgrover** [comment] 2022-04-17 04:00
@dormerod
I've changed some things around which "could" cause this sign-out issue and fixed some minor bugs. I'm still unable to reproduce the exact issue you described but I'm hoping that the changes I made fixes the sign-out issue. 

Just open Brisqi when internet is available and you should receive a new update(v0.3.2). Please let me know if this fixes the issue.

**Comment by dormerod** [comment] 2022-04-17 04:22
Thanks @ashgrover. I'm very sorry to report that the issue has persisted.

Just now I:

- downloaded 0.3.2
- closed the app, restarted, confirmed version 0.3.2
- closed and restarted (again) with internet -- everything seemed to be normal
- closed, turned off all data, restarted again -- the login screen appeared after a moment :(

It's strange that this issue is still so hard to reproduce because it's consistently predictable at this end. Could there be a (non-default) setting in Android that might cause this to happen?

Edit: I'll also see if I can reproduce this on another phone later. And happy Easter.

**Comment by ashgrover** [comment] 2022-04-17 18:36
@dormerod Thanks for the quick response and happy Easter to you as well :)

It is so odd that it's still happening on your device. It could be that secure storage is not getting the credentials for some weird reason. I've pushed out another update (v0.3.3) with some minor changes which would clear Brisqi data in secure storage if it cannot retrieve it. 

Before you update the app, could you please clear Brisqi data manually and try again? You can do that by going to Settings -> Storage -> Apps -> Brisqi app - then clear cache and all other data. The exact steps might be different for your device. You may have to sign-in again after you clear the data.

Please let me know if it works.

**Comment by dormerod** [comment] 2022-04-17 23:44
@ashgrover thanks. I just cleared the data and tested this per your comment above.

Unfortunately, it still hasn't resolved the issue.

The app has updated to the 0.3.3 OTA and I tested it offline a few times, reconnecting to the internet to log in again in between each failed attempt (and clearing the data a couple of times as well).

I also tested the mobile app on a family member's phone, which is very similar model but slightly newer than mine.

Initially; after installing for the first time, viewing one of my boards, going offline, closing the app completely and then restarting it; it was possible to view the board that had already loaded and other boards had a message about being offline (for clarity, this was on the new phone). I assume that's how the app is normally supposed to work.

However, after testing again, I encountered the same issue on the new phone and had to log in again. I'm not sure if I made an error in my testing, but this is the first time I've seen the offline behaviour work as intended, albeit on another device.

Sorry that I don't have anything more useful to report at this stage. I'll dig out some older phones and charge them to further test this later. I'm a bit concerned about how much of your time this issue is taking up.

Just to be clear, the specific process for reproducing this bug is:

- open Brisqi
- confirm that you're logged in and that it's working normally
- disable WiFi
- disable mobile data
- view the running apps (which is a `|||` icon with three vertical lines on my phone)
- find Brisqi and swipe up to close it
- open Brisqi again (while still offline)
- after a moment of trying to load, the app displays the login screen.

I'll let you know if I figure out anything else that might be useful.

**Comment by ashgrover** [comment] 2022-04-18 06:38
@dormerod Thank you so much for testing the update and trying it on a different phone, and don't worry about this issue taking up my time because other users could also potentially face the same issue in the future so it's important for me to figure this out. Also it provides me with a better understanding of how Android phones from different manufactures behave, this will only help me in debugging issues in the future better as I gain more insight. Also, please don't feel pressured to respond immediately, respond whenever you have time as I can understand it's also consuming your time.

>Initially; after installing for the first time, viewing one of my boards, going offline, closing the app completely and then restarting it; it was possible to view the board that had already loaded and other boards had a message about being offline (for clarity, this was on the new phone). I assume that's how the app is normally supposed to work.

Correct, that is the expected behaviour. Brisqi downloads data only for the board which the user has opened while being online, so only that board will be available offline.

I've followed the steps provided exactly as mentioned and I still can't reproduce it on any of the phones I have. This is quite puzzling. I've pretty much ruled out most things which could cause this issue. The app isn't crashing, it only signs out, so that means it's not able to either get credentials from the secure storage or the data from the sqlite db. I feel that most likely it's not able to get it from secure storage, but I don't know why that is, because all Android phones have this secure storage feature by default(as far as I know).

When a user runs Brisqi and the first time they open a board, it'd take a couple of seconds to download data and then the board would be displayed, the second time it should open immediately(as shown in the video below). The fact that it opens quickly the second time means that it's able to get the data from sqlitedb as expected. When you open a board "second" time, does it open quickly or does it feel like it's taking the time to download the data and then display?

I've attached a video recording below in case and followed the steps as you described. Please let me know if I missed anything in the video. 

https://user-images.githubusercontent.com/5951074/163761493-1aa70b57-7ccd-42fb-9ea6-46d3f4e2230a.mov

**Comment by dormerod** [comment] 2022-04-28 00:20
Just tested this with update 0.3.5 and guess what @ashgrover? It's fixed! :tada:

Thank you for all the work sorting this one out. It means a lot.

I'll continue to monitor the offline behaviour on mobile and create a new issue if there are any wrinkles, but this bug is resolved and you should be able to close it when you're ready :smile:

**Comment by ashgrover** [comment] 2022-04-28 06:00
@dormerod  That's great to hear. Thanks for testing it out and confirming that it's fixed. Turns out for some reason Brisqi app wasn't able to detect network connection state correctly on your phone. The particular library I was using to determine if internet is reachable worked on some phones and didn't on others. In your case, Brisqi always received "connected" state even when the phone is not connected to the internet.

I changed the library to much more stable and popular library, but this library also behaves differently on different phones when there's a network change, for example - on some Android phones when going from wifi to cellular data while Brisqi is running, library thinks phone is offline so Brisqi will switch to offline mode unless Brisqi is restarted, then it detects cellular data. This only happens sometimes based on my testing. On iOS/iPhone it works fine.

Majority of the time things work fine on Android phones, but in few cases it becomes a bit of a challenge because some of the things are not standardized on Android phones. It's getting better, albeit slowly.

Closing this issue as it's now resolved :)

**Closed as completed by ashgrover** 2022-04-28 06:00 UTC
Labels: bug
