### ISSUE TITLE
Long card titles get clipped on mobile

### ISSUE THREAD

**Issue by dormerod** [brisqapp/issue-tracker#25] opened 2022-03-25 09:34 UTC
**Brisqi version:** 0.7.3

**Brisqi plan:** standard

**Device:** mobile

**Environment:** Android 11

## What happened?

I created a card with an unusually long title. I could read the full card title in the desktop app, but on the mobile app I could only read three wrapped lines:

![card-title](https://user-images.githubusercontent.com/7741478/160094292-76d99e1e-7570-4509-be6d-5bab3af95c94.jpeg)

## What I expected to happen

I expected to be able to read the full card title text.

This may be the intended functionality and could be considered fine. Please feel free to close this ticket if that's the case (I won't be offended).

Since first noting this issue more than a month ago, I suspect some updates have been pushed out that improved this and some similar issues. I'm still posting it here just in case it's not the intended behaviour.

## Steps to reproduce

1. create a card with an unusually long title and go back to the board view
2. view it in the desktop app and it displays all the text that you're allowed to enter
3. view it in the mobile app and it only displays the first three lines of wrapped text.

**Comment by ashgrover** [comment] 2022-04-10 00:11
@dormerod 
Thanks for reporting. This is not a bug, this is intentional. It's a bit tricky to support dynamic card heights on a mobile app because of dragging and dropping functionality. Currently, the card supports 3 types of height to display items such as text, subtasks/comments and labels. The text part of the card gets a maximum 3 lines to occupy, if it gets any longer, it clips it and shows "..."(ellipsis) to convey that text is longer than displayed here. At this point I expect the user to click on the card to read more. I haven't found a better way to support drag and drop functionality with dynamic heights as it is quite tricky as I mentioned before. If in future I come across a better way, I'll implement it. Closing this for now as it's not a bug.

**Closed as completed by ashgrover** 2022-04-10 00:11 UTC

**Comment by dormerod** [comment] 2022-04-11 04:51
Thanks for taking the time to explain Ash. It sounds like a reasonable compromise :smile:
