### ISSUE TITLE
Dragging Cards around cause duplicate ghost tiles, crash.

### ISSUE THREAD

**Issue by ShoarW** [brisqapp/issue-tracker#38] opened 2022-08-19 09:23 UTC
Hello,

A previous version of this app that I've used didn't use to do this, but I haven't used it in a while and was giving it a go again today.

Ran into this issue where I was just trying to drag a card to another column and it created a whole bunch of ghost tiles, then if I dragged the card back onto the ghost tile it'll crash.

Ultimately any changes that I make to the board don't save at all.

See attached video.

https://user-images.githubusercontent.com/1826036/185588213-79509987-6c43-41a6-ac11-f745e90ac143.mp4

**Comment by ashgrover** [comment] 2022-08-20 18:55
@ShoarW Thanks for reporting this issue. This issue really odd, I couldn't reproduce this issue on my end at all. 

You mentioned that you had a previous version of the app. Do you recall what version you had before? I've made few updates which upgrades the database and resolves few other issues. 

In the meantime, could you try following:
- Create a backup of your data by going to Settings -> Backup -> Backup Data.
- Move backup file  `%AppData%\Brisqi\backup.brisqi` to some other safe location.
- Uninstall the app.
- Delete the  `%AppData%\Brisqi` directory - this is where all the data is stored.
- Install Brisqi app again, run the app and then move the backup file to  `%AppData%\Brisqi\` directory.
- Restore the backup data from Settings -> Backup -> Restore Data.

If you don't care about your data then you can skip all the backup process and proceed with the removal of  `%AppData%\Brisqi` directory and installing the app again.

Pleas let me know if this resolves the issue.

**Comment by ShoarW** [comment] 2022-08-21 07:41
Unfortunately uninstalling and reinstalling the app did not appear to work, I didn't load in my backup file and ended up using just the board that you get by default and it still appears to do the bug.

I checked my downloads and it appeared to be 0.7.0 but when I ran it had the same issue, I deleted the AppData settings again and selected the free plan.

I noticed that's a lot smoother on the free plan, when I signed in I got spammed with "A new update is available" which appeared to slow down the application a lot and I could trigger the bug over and over.

![image](https://user-images.githubusercontent.com/1826036/185780866-5c6442b1-e697-4146-887f-b977b13eca5c.png)

When I was on the free plan, I couldn't get it to trigger except for the one time where the notification appeared and a singular ghost tile appeared but that was it.

When I updated I was still in the free plan and could not get it to trigger.

Then I signed in and got the exact same issue again.

That's about as much as I can narrow it down. Hope that helps.

**Comment by ashgrover** [comment] 2022-08-21 23:01
@ShoarW  Thanks for the detailed information. Unfortunately, I still can't reproduce the issue.

I installed Brisqi v0.7.0 and made sure to remove Brisqi's folder in AppData before installing. Everything worked as expected in v0.7.0, no ghost tiles and I got the update notification once. Then I signed in and performed an update to v0.8.1(latest version), the update went smoothly. I dragged and dropped cards many times, didn't see any ghost tiles. I deleted all boards and created new ones and still didn't see any ghost tiles. Deleted the Brisqi folder in AppData again and ran the app again, everything worked as expected.

Do you have older version of Brisqi running on multiple computers somewhere with same user signed in at the same time? There's one edge-case I can think of multiple update notifications but it's rare that it would happen and this edge-case was fixed in version 0.8.0.

Could you please try downloading latest version of Brisqi from the [website ](https://brisqi.com/pricing) and try those steps I mentioned in my previous post? Currently the latest version is v0.8.1.

Thanks again,
Ash

**Comment by ShoarW** [comment] 2022-08-22 00:48
@ashgrover I can get the behavior to replicate on multiple machines, by quitting Brisqi, starting it up and immediately start dragging the tile around without dropping it, when the update notification pops up a ghost tile will be created and you will be stuck with it. I managed to replicate this on my work machine on 0.7.3, I updated to 0.8.1 and the issue still occurs if you do it right after the application starts up.

**Comment by ashgrover** [comment] 2022-08-22 03:42
@ShoarW Thanks for the response. I'm able to reproduce the issue now, dragging immediately after starting the app causes the ghost tile issue. I probably know what's causing this issue, it will be fixed in the next release.

Ash

**Comment by ashgrover** [comment] 2022-10-16 06:18
This issue is now fixed in v0.9.0.

**Closed as completed by ashgrover** 2022-10-16 06:18 UTC
Labels: bug
